server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  cron_worker:
    addr: http://127.0.0.1:8080/xxl-job-admin
    access_token: default_token
    executor_ip: 127.0.0.1
    executor_port: "9999"
    registry_key: cms-jobs

data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 500
    write_timeout: 500
    database: 0
    pool_size: 100
  local_cache:
    size: 10000
